### ISSUE TITLE
springSecurityFilterChain bean missing

### ISSUE THREAD

**Issue by bap-dev** [edu-sharing/edu-sharing-projects-community#9]
on a kubernetes cluster when enabling saml with:
``` 
saml:
            enabled: true
```
we are getting 
```
SCHWERWIEGEND: Ausnahme beim Starten des Filters [springSecurityFilterChain]             
 org.springframework.beans.factory.NoSuchBeanDefinitionException: No bean named 'springSecurityFilterChain' available                                                                                                                              org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanDefinition(DefaultListableBeanFactory.java:893)                                                                                                                org.springframework.beans.factory.support.AbstractBeanFactory.getMergedLocalBeanDefinition(AbstractBeanFactory.java:1316)                                                                                                                  org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)                                                                                                                                      org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:204)                                                                                                                                        org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1172
org.springframework.web.filter.DelegatingFilterProxy.initDelegate(DelegatingFilterProxy.java:332)                                                                                                                                          
org.springframework.web.filter.DelegatingFilterProxy.initFilterBean(DelegatingFilterProxy.java: 240)      
...
```
please provide some documentation!

**Comment by torsten-simon** [comment]
Hi,

in order to use SSO, please also provide the relevant config in the lightbend config files. You can do this BEFORE enabling saml via Admin Tools / System Config or directly via helm configs:
```yaml
edusharing_repository:
    edusharing_repository_service:
        config:
            override:
                config:
                    application:
                        settings: |
                          spring.profiles.active=samlEnabled
                          security.sso.saml{
                              useHomeApplicationKeys: true
                              idp: {
                                  metadata: {
                                      url: "http://"
                                  }
                              }
                          }

```

Details on what is possible to be overriden (additional parameters) can be found in the default config file:
https://github.com/edu-sharing/edu-sharing-community-repository/blob/maven/fixes/9.0/config/defaults/src/main/resources/edu-sharing.reference.conf

Best Regards
Torsten
